# Generated by Django 3.0.8 on 2020-07-19 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Pro_image')),
                ('problem_type', models.CharField(blank=True, choices=[('H', 'Hardware problem'), ('S', 'Software problem'), ('N', 'Network problem')], max_length=200, null=True)),
                ('solution', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
