# Generated by Django 3.0.8 on 2020-07-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200719_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name_plural': 'Solutions'},
        ),
    ]
