# Generated by Django 3.0.8 on 2020-07-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='solution_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Solution'),
        ),
    ]
