# Generated by Django 3.0.8 on 2020-08-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200810_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='problem_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
