# Generated by Django 3.0.8 on 2020-08-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_problems_problem_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='images',
            field=models.FileField(upload_to='user_profile'),
        ),
    ]
