# Generated by Django 3.1 on 2020-08-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200810_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Pro_image'),
        ),
    ]
