# Generated by Django 3.0.8 on 2020-08-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200810_1833'),
        ('core', '0016_comments_created'),
    ]

    operations = [
    ]
