# Generated by Django 3.0 on 2020-08-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_userprofile_expert_to'),
        ('core', '0017_merge_20200811_1713'),
    ]

    operations = [
    ]
